#!/bin/sh

# Verbosity
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" 

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto"

# Get faster
alias \
    xmhs="vim ${XMONAD_CONFIG_DIR}/xmonad.hs" \
    zrc="vim ${ZDOTDIR}/.zshrc" \
    vimrc="vim ${XDG_CONFIG_HOME}/nvim/init.lua" \
    vifm="${XDG_CONFIG_HOME}/vifm/scripts/vifmrun" \
    fin="~/.private/Finanza/fin" \

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"
