#!/bin/sh

# Verbosity
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" 

# Colorize commands when possible
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto"

# Get faster
alias \
    xmhs="cd ${XMONAD_CONFIG_DIR}; $EDITOR xmonad.hs" \
    zrc="cd ${ZDOTDIR}; $EDITOR .zshrc" \
    vimrc="cd ${XDG_CONFIG_HOME}/nvim/; $EDITOR init.lua" \
    vifm="${XDG_CONFIG_HOME}/vifm/scripts/vifmrun" \
    fins="$HOME/private/Finanza/fin" \
    fine="cd $HOME/.private/Finanza/; $EDITOR 2022.csv" \

# Use neovim for vim if present
[ -x "$(command -v nvim)" ] && alias vim="nvim"
