#!/bin/sh

# Start icon tray
trayer --edge top --align right --widthtype request --padding 6 --SetDockType true --SetPartialStrut true --expand true --monitor 0 --transparent true --alpha 0 --tint 0x2e3440  --height 22 &

# Start Redshift
redshift-gtk &

# Load .Xresources
xrdb -merge ${XDG_CONFIG_HOME:-$HOME/.config}/x11/Xresources

# Set default cursor
xsetroot -cursor_name left_ptr

# Get speedy keys
xset r rate 210 40

# Disable screen save for inactivity
xset s off

# Lock the screen before going to sleep
xss-lock -- /usr/local/bin/slock &

# Set background
nitrogen --restore &

# Start picom
picom &

# Start dunst
dunst &
